version: 2
jobs:
  build: 
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.12

    steps: 
      - checkout 
      - run:
          name: Build server
          command: |
            cd server/cmd/server
            go build
