version: 2.1

orbs:
  go: circleci/go@1.4.0

jobs:
  build: 
    executor:
      name: go/default
      tag: '1.15'
    working_directory: ~/project/server
    steps: 
      - checkout:
          path: ~/project
      - go/mod-download-cached
      - run:
          name: Build server
          command: |
            cd cmd/server
            go build

workflows:
  main:
      jobs:
        - build

