version: 2.1

orbs:
  go: circleci/go@1.4.0

jobs:
  build: 
    executor:
      name: go/default
      tag: '1.15'
    steps: 
      - checkout 
      - run:
          name: Move to server directory
          command: |
            cd server/cmd/server
      - go/mod-download-cached
      - run:
          name: Build server
          command: |
            go build

workflows:
  main:
      jobs:
        - build

