version: 2.1
jobs:
  build: 
    executor:
      name: go/default
      tag: '1.15'
    steps: 
      - checkout 
      - go/mod-download-cached

orbs:
  go: circleci/go@1.12
  version: 2.1
  workflows:
    main:
        jobs:
          - build
