version: 2.1

orbs:
  go: circleci/go@1.14

jobs:
  build: 
    executor:
      name: go/default
      tag: '1.15'
    steps: 
      - checkout 
      - go/mod-download-cached
      - run:
          name: Build server
          command: |
            cd server/cmd/server
            go build

workflows:
  main:
      jobs:
        - build

